<?php

/**
 * @var Vashchak\FilesCatalog\Block\Object $block
 */
$object = $block->getModel();

?>

<style>
  table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
  td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
  tr:nth-child(even) { background-color: #dddddd; }
  .post-id{width:2%} .post-name{width:30%}

</style>

<div class="breadcrumbs">
    <?php echo $block->getBreadCrumbs(); ?>
</div>

<h1><?php echo $object->getTitle(); ?></h1>
<table>
  <tr>
    <th>Description</th>
  </tr>
    <?php
    echo '<tr>
              <td>'.$object->getDescription().'</td>
          </tr>';
    ?>
</table>

</body>
</html>